"""FastExpr generation helpers."""

from .knowledge_pack import build_knowledge_packs
from .budget import (
    BudgetBlockedError,
    LLMBudgetConfig,
    aggregate_usage_from_events,
    build_budget_console_payload,
    build_budget_event_payload,
    build_kpi_payload,
    build_reactor_status_payload,
    can_use_expansion_reserve,
    compact_knowledge_bundle,
    collect_seen_combinations,
    enforce_alpha_prompt_budget,
    estimate_cost_usd,
    extract_prompt_completion_tokens,
    load_llm_budget,
    rough_token_estimate,
)
from .openai_provider import (
    LLMCallResult,
    OpenAILLMSettings,
    OpenAIProviderError,
    OpenAIResponsesJSONClient,
)
from .prompting import (
    ParseFailure,
    build_alpha_maker_prompt,
    build_fastexpr_prompt,
    build_gated_fastexpr_prompt,
    build_idea_researcher_prompt,
    parse_candidate_alpha,
    parse_idea_spec,
    parse_with_format_repair,
    repair_json_text,
)
from .validation_gate import ValidationGate, ValidationGateResult, ValidationIssue

__all__ = [
    "LLMCallResult",
    "OpenAILLMSettings",
    "OpenAIProviderError",
    "OpenAIResponsesJSONClient",
    "BudgetBlockedError",
    "LLMBudgetConfig",
    "aggregate_usage_from_events",
    "build_budget_console_payload",
    "build_budget_event_payload",
    "build_kpi_payload",
    "build_reactor_status_payload",
    "can_use_expansion_reserve",
    "compact_knowledge_bundle",
    "collect_seen_combinations",
    "enforce_alpha_prompt_budget",
    "estimate_cost_usd",
    "extract_prompt_completion_tokens",
    "load_llm_budget",
    "rough_token_estimate",
    "ParseFailure",
    "build_alpha_maker_prompt",
    "build_fastexpr_prompt",
    "build_gated_fastexpr_prompt",
    "build_idea_researcher_prompt",
    "parse_candidate_alpha",
    "parse_idea_spec",
    "parse_with_format_repair",
    "repair_json_text",
    "build_knowledge_packs",
    "ValidationGate",
    "ValidationGateResult",
    "ValidationIssue",
]
